---
apiVersion: v1
kind: ConfigMap
metadata:
  name: upload-bucket-config
data: {}
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: upload-bucket-config
spec:
  to:
    name: upload-bucket-config
    kind: configmap
    key: uploads_bucket_arn
  from:
    path: ".status.ackResourceMetadata.arn"
    resource:
      group: s3.services.k8s.aws
      kind: Bucket
      name: sciety-bonfire-uploads--${environment_name}
