apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bonfire-uploads-bucket
  namespace: sciety
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: sciety-deployment
    namespace: flux-system
  path: ./templated-kustomizations/bonfire/awsrole
  prune: true
  targetNamespace: sciety
  dependsOn:
    - name: bonfire-uploads-bucket
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: sciety-bonfire-uploads--prod-config
    substitute:
      environment_name: prod
      cluster_oidc_arn: ${cluster_oidc_arn}
      cluster_oidc_url: ${cluster_oidc_url}
      bonfire_namespace: sciety
