apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bonfire
  namespace: sciety
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: sciety-deployment
    namespace: flux-system
  path: ./templated-kustomizations/bonfire/web
  prune: true
  targetNamespace: sciety
  dependsOn:
    - name: bonfire-database
    - name: bonfire-uploads-bucket
    - name: bonfire-awsrole
  images:
    - name: bonfirenetworks/bonfire
      newName: bonfirenetworks/bonfire # {"$imagepolicy": "sciety:bonfire-open-science-rc:name"}
      newTag: 1.0.0-rc.2.28-open_science-amd64 # {"$imagepolicy": "sciety:bonfire-open-science-rc:tag"}
      digest: sha256:2eac03195dd623e5623c56b83d730356a3b2bf068eaed0ddd226bbfccd60c524 # {"$imagepolicy": "sciety:bonfire-open-science-rc:digest"}
  postBuild:
    substituteFrom:
      - kind: Secret
        name: bonfire-connection-details
      - kind: ConfigMap
        name: bonfire--prod-role-config
    substitute:
      environment_name: prod
      replicas: "1"
      hostname: "discussions.sciety.org"
      uploads_bucket_name: sciety-bonfire-uploads--prod
      uploads_bucket_region: us-east-1
      uploads_bucket_endpoint: s3.us-east-1.amazonaws.com
      secret_name: bonfire-secrets
      meili_search_instance: http://meilisearch:7700
