apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "./meilisearch.yaml"
  - "./postgresql.yaml"
  - "./secrets.yaml"
  - "./uploads-bucket.yaml"
  - "./awsrole.yaml"
  - "./bonfire.yaml"
  - "./updateautomation.yaml"
namespace: sciety
