apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "./bonfire.yaml"
  # percona postgres-operator
  - "./postgresql.yaml"
  # cnpg operator
  - "./database"
  - "./secrets.yaml"
  - "./uploads-bucket.yaml"
  - "./awsrole.yaml"

namespace: sciety
