---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bonfire-database
  namespace: sciety
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kustomizations/utils/pg-cluster
  prune: true
  targetNamespace: sciety
  postBuild:
    substitute:
      # Deployment values
      cluster_name: bonfire
      postgres_version: "16"
      storage_size: 10Gi
      storage_class: sciety-gp3

      # Backup values
      project: sciety-bonfire
      aws_backup_service_account_role_arn: ${aws_backup_service_account_role_arn}
      aws_backup_s3_bucket: ${aws_backup_s3_bucket}
      aws_region: ${aws_region}
  patches:
    - target:
        kind: PerconaPGCluster
      patch: |
        - op: add
          path: /spec/proxy/pgBouncer/config/global/client_tls_sslmode
          value: allow
