apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bonfire-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: bonfire-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: sciety-team/bonfire-secrets
