---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: bonfire
  namespace: sciety
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: sciety-deployment
    namespace: flux-system
  update:
    strategy: Setters
    path: ./manifests/bonfire/bonfire.yaml
  git:
    commit:
      author:
        name: Fluxbot
        email: flux@elifesciences.org
      messageTemplate: |
        deploy({{ .AutomationObject }}): Automatic deploy

        Files:
        {{ range $filename, $_ := .Changed.FileChanges -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $changes := .Changed.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Namespace }}/{{ $resource.Name }}
          Changes:
        {{- range $_, $change := $changes }}
          - {{ $change.Setter }}: {{ $change.OldValue }} -> {{ $change.NewValue }}
        {{ end -}}
        {{ end -}}
