apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: sciety-events-export
spec:
  name: sciety-events-export
  policy: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Principal": {
            "AWS": [
              "arn:aws:iam::512686554592:user/data-pipeline"
            ]
          },
          "Action": [
            "s3:ListBucket"
          ],
          "Effect": "Allow",
          "Resource": "arn:aws:s3:::sciety-events-export"
        },
        {
          "Principal": {
            "AWS": [
              "arn:aws:iam::512686554592:user/data-pipeline"
            ]
          },
          "Action": [
            "s3:GetObject"
          ],
          "Effect": "Allow",
          "Resource": "arn:aws:s3:::sciety-events-export/*"
        }
      ]
    }

---

apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: sciety-events-shipper
spec:
  name: sciety-events-shipper
  assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": "${cluster_oidc_arn}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "ForAnyValue:StringEquals": {
                "${cluster_oidc_url}:sub": [
                  "system:serviceaccount:sciety:sciety--demo--sciety-export-events",
                  "system:serviceaccount:sciety:sciety--staging--sciety-export-events",
                  "system:serviceaccount:sciety:sciety--prod--sciety-export-events"
                ]
              }
            }
          }
        ]
      }
  inlinePolicies:
    giveAccessToScietyEventsExportBucket: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
           "Action": [
             "s3:*"
           ],
           "Effect": "Allow",
           "Resource": "arn:aws:s3:::sciety-events-export"
         },
         {
           "Action": [
             "s3:*"
           ],
           "Effect": "Allow",
           "Resource": "arn:aws:s3:::sciety-events-export/*"
         }
        ]
      }

---

apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: sciety-event-shipper-role-arn
spec:
  to:
    name: sciety-event-shipper-config
    kind: configmap
    key: EVENT_SHIPPER_ROLE_ARN
  from:
    path: ".status.ackResourceMetadata.arn"
    resource:
      group: iam.services.k8s.aws
      kind: Role
      name: sciety-events-shipper

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sciety-event-shipper-config
data: {}
