apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: sciety-events-export
spec:
  name: sciety-events-export

---

apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: sciety-events-shipper
spec:
  name: sciety-events-shipper
