apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "./sciety-git-repository.yaml"
  - "./sciety-namespace.yaml"
  - "./events-export-bucket.yaml"
  - "./ncrc-sheet-key.yaml"
  - "./monitoring"
  - "./sciety-staging"
  - "./sciety-prod"
  - "./sciety.org-ack-maintained-dns-records.yaml"
  - "./bonfire"
  - "./dev-discussions-dns.yaml"

namespace: sciety
