apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "./sciety-git-repository.yaml"
  - "./sciety-namespace.yaml"
  - "./events-export-bucket.yaml"
  - "./grafana-dashboard-test.yaml"
  - "./sciety-demo"
  - "./sciety-staging"
  - "./sciety-prod"


namespace: sciety
