apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sciety--ncrc-sheet-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: ncrc-sheet-key
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: sciety-team/sciety-ncrc-sheet-key
