apiVersion: route53.services.k8s.aws/v1alpha1
kind: RecordSet
metadata:
  name: test-txt-record
spec:
  name: sciety.org.
  recordType: TXT
  ttl: 300
  hostedZoneID: Z09890101D2MRHJUSMZYW
  resourceRecords:
    - value: "hello"
    - value: "world"
