apiVersion: route53.services.k8s.aws/v1alpha1
kind: RecordSet
metadata:
  name: txt-records
spec:
  recordType: TXT
  ttl: 300
  hostedZoneID: Z09890101D2MRHJUSMZYW
  resourceRecords:
    - value: "v=spf1 include:_spf.google.com include:143759941.spf05.hubspotemail.net ip4:89.16.178.40 ~all"
    - value: "google-site-verification=CkWhogOskZm7nRTmjdHiD8q2NbfXOns-vp5qeHEK_5w"
    - value: "facebook-domain-verification=hr2usdynx8j2iv4mpn7i7ka0nkwaa1"
    - value: "heritage=external-dns,external-dns/owner=flux-cluster,external-dns/resource=ingress/sciety/sciety--prod--frontend"
---
apiVersion: route53.services.k8s.aws/v1alpha1
kind: RecordSet
metadata:
  name: mx-records
spec:
  recordType: MX
  ttl: 300
  hostedZoneID: Z09890101D2MRHJUSMZYW
  resourceRecords:
    - value: 1 ASPMX.L.GOOGLE.COM.
    - value: 5 ALT1.ASPMX.L.GOOGLE.COM.
    - value: 5 ALT2.ASPMX.L.GOOGLE.COM.
    - value: 10 ALT3.ASPMX.L.GOOGLE.COM.
    - value: 10 ALT4.ASPMX.L.GOOGLE.COM.
---
apiVersion: route53.services.k8s.aws/v1alpha1
kind: RecordSet
metadata:
  name: rebrandly-go-sciety
spec:
  name: go
  recordType: A
  ttl: 3600
  hostedZoneID: Z09890101D2MRHJUSMZYW
  resourceRecords:
    - value: 52.72.49.79
---
apiVersion: route53.services.k8s.aws/v1alpha1
kind: RecordSet
metadata:
  name: folk-sendgrid-1
spec:
  name: 1._domainkey
  recordType: CNAME
  ttl: 300
  hostedZoneID: Z09890101D2MRHJUSMZYW
  resourceRecords:
    - value: 1.domainkey.u37793993.wl244.sendgrid.net
---
apiVersion: route53.services.k8s.aws/v1alpha1
kind: RecordSet
metadata:
  name: folk-sendgrid-2
spec:
  name: 12._domainkey
  recordType: CNAME
  ttl: 300
  hostedZoneID: Z09890101D2MRHJUSMZYW
  resourceRecords:
    - value: 12.domainkey.u37793993.wl244.sendgrid.net
---
apiVersion: route53.services.k8s.aws/v1alpha1
kind: RecordSet
metadata:
  name: folk-sendgrid-3
spec:
  name: em3684
  recordType: CNAME
  ttl: 300
  hostedZoneID: Z09890101D2MRHJUSMZYW
  resourceRecords:
    - value: u37793993.wl244.sendgrid.net
