apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: sciety-coar-ingestion-errors
  labels:
    alert-type: victorialogs
spec:
  groups:
    - name: coar-based-ingestion
      type: vlogs
      rules:
        - alert: PersistentCoarIngestionError
          expr: |
            Error AND kubernetes.pod_labels.app.kubernetes.io/component:="coar-based-ingestion" AND kubernetes.pod_labels.app.kubernetes.io/instance:="sciety--prod" AND _time:1h | unpack_json | stats by (payload.evaluationCommand.groupId, payload.evaluationCommand.expressionDoi, payload.evaluationCommand.evaluationLocator) count() as errors
          condition: "errors > 1"
          annotations:
            summary: "COAR ingestion error repeated for the same evaluation command in the past hour"
            description: "groupId={{ $labels.payload_evaluationCommand_groupId }} expressionDoi={{ $labels.payload_evaluationCommand_expressionDoi }} evaluationLocator={{ $labels.payload_evaluationCommand_evaluationLocator }} has failed {{ $value }} times in the past hour."
          labels:
            severity: error
