{
 "title": "Sciety application health",
 "tags": [ "sciety" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "bucket",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "[RATE] Requests / 1m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kubernetes.pod_labels.app.kubernetes.io/name: \"sciety\"\nAND kubernetes.pod_labels.app.kubernetes.io/instance:\"sciety--demo\"\nAND kubernetes.pod_labels.app.kubernetes.io/component:\"frontend\"\nAND \"Sent HTTP response\"\n| extract_regexp '\"status\":(?P<status>[2-5]+)[0-9]{2},'\n| stats by(status) count() logs_total\n",
     "legendFormat": "{{status}}xx"
    }
   ]
  },
  {
   "title": "[DURATION] Request duration [s] / $bucket",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kubernetes.pod_labels.app.kubernetes.io/name: \"sciety\"\nAND kubernetes.pod_labels.app.kubernetes.io/instance:\"sciety--demo\"\nAND kubernetes.pod_labels.app.kubernetes.io/component:\"frontend\"\nAND \"Sent HTTP response\"\n| extract '\"durationInMs\":<duration_msecs>,'\n| math round(duration_msecs / 1000) as request_duration_seconds\n| stats\n  quantile(0.5, request_duration_seconds) p50,\n  quantile(0.9, request_duration_seconds) p90,\n  quantile(0.99, request_duration_seconds) p99,\n  avg(request_duration_seconds) avg\n"
    }
   ]
  },
  {
   "title": "[SATURATION] CPU Usage [cores used]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"sciety\", pod=~\"sciety--demo--frontend.*\", cpu=\"total\", container=\"app\"})",
     "legendFormat": "{{image}}"
    }
   ]
  }
 ]
}