apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "./coar-notify-inbox-rendered-kustomization.yaml"
  - "./helm-release.yaml"
  - "./public-env-var-configmap.yaml"
  - "./secret-env-vars.yaml"
  - "./rds-postgres.yaml"

namespace: sciety
