apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coar-notify-inbox--prod
  namespace: sciety
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: sciety-deployment
    namespace: flux-system
  path: ./kustomizations/coar-notify-inbox
  prune: true
  targetNamespace: sciety
  postBuild:
    substitute:
      environment_name: prod
      db_chart_version: 1.19.0
