---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: bonfire
spec:
  interval: 5m
  image: bonfirenetworks/bonfire
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: bonfire-open-science
spec:
  imageRepositoryRef:
    name: bonfire
  filterTags:
    pattern: ^(?P<semver>.*?)-open_science-amd64
    extract: 'v$semver.0'
  policy:
    semver:
      range: '*'
  digestReflectionPolicy: IfNotPresent
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: bonfire-open-science-rc
spec:
  imageRepositoryRef:
    name: bonfire
  filterTags:
    pattern: ^1\.0\.0-rc\.(?P<major>\d+)\.(?P<minor>\d+)-open_science-amd64
    extract: '$major.$minor.0'
  policy:
    semver:
      range: '*'
  digestReflectionPolicy: IfNotPresent
