---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: bonfire
spec:
  interval: 5m
  image: bonfirenetworks/bonfire
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: bonfire
spec:
  imageRepositoryRef:
    name: bonfire-open_science
  filterTags:
    pattern: '^(?P<semver>[0-9]+\.[0-9]+\.[0-9]+)-open_science-amd64'
    extract: '$semver'
  policy:
    semver:
      range: '*'
