---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonfire--${environment_name}
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: web
        image: bonfirenetworks/bonfire:latest-open_science
