---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonfire--${environment_name}
spec:
  replicas: ${replicas:-1}
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      initContainers:
      - name: migration
        image: bonfirenetworks/bonfire:1.0.0-rc.1.19-open_science-aarch64@sha256:b63e46783c5f6458aeabd8d63ccb0d81fa7ce264340da246ffd72d24075922bd
        args:
          - ./bin/bonfire
          - eval
          - Bonfire.Common.Repo.migrate
        env:
        - name: POSTGRES_HOST
          value: "${POSTGRES_HOST}"
        - name: POSTGRES_USER
          value: "${POSTGRES_USER}"
        - name: POSTGRES_DB
          value: "${POSTGRES_DB}"
        - name: POSTGRES_PASSWORD
          value: "${POSTGRES_PASSWORD}"
        - name: SECRET_KEY_BASE
          value: "${SECRET_KEY_BASE}"
        - name: SIGNING_SALT
          value: "${SIGNING_SALT}"
        - name: ENCRYPTION_SALT
          value: "${ENCRYPTION_SALT}"
      containers:
      - name: web
        image: bonfirenetworks/bonfire:1.0.0-rc.1.19-open_science-aarch64@sha256:b63e46783c5f6458aeabd8d63ccb0d81fa7ce264340da246ffd72d24075922bd
        env:
        - name: POSTGRES_HOST
          value: "${POSTGRES_HOST}"
        - name: POSTGRES_USER
          value: "${POSTGRES_USER}"
        - name: POSTGRES_DB
          value: "${POSTGRES_DB}"
        - name: POSTGRES_PASSWORD
          value: "${POSTGRES_PASSWORD}"
        - name: SECRET_KEY_BASE
          value: "${SECRET_KEY_BASE}"
        - name: SIGNING_SALT
          value: "${SIGNING_SALT}"
        - name: ENCRYPTION_SALT
          value: "${ENCRYPTION_SALT}"
        ports:
        - name: http
          containerPort: 4000
