---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonfire--${environment_name}
spec:
  replicas: ${replicas:-1}
  template:
    spec:
      initContainers:
      - name: migration
        image: bonfirenetworks/bonfire:latest-open_science@sha256:3c8bbde67ec3159e239a7c0d148975febae7da918cb84999530a6735f3b80581
        args:
          - ./bin/bonfire
          - eval
          - Bonfire.Common.Repo.migrate
        env:
        - name: POSTGRES_HOST
          value: "${POSTGRES_HOST}"
        - name: POSTGRES_USER
          value: "${POSTGRES_USER}"
        - name: POSTGRES_DB
          value: "${POSTGRES_DB}"
        - name: POSTGRES_PASSWORD
          value: "${POSTGRES_PASSWORD}"
        - name: SECRET_KEY_BASE
          value: "${SECRET_KEY_BASE}"
        - name: SIGNING_SALT
          value: "${SIGNING_SALT}"
        - name: ENCRYPTION_SALT
          value: "${ENCRYPTION_SALT}"
      containers:
      - name: web
        image: bonfirenetworks/bonfire:latest-open_science@sha256:3c8bbde67ec3159e239a7c0d148975febae7da918cb84999530a6735f3b80581
        env:
        - name: POSTGRES_HOST
          value: "${POSTGRES_HOST}"
        - name: POSTGRES_USER
          value: "${POSTGRES_USER}"
        - name: POSTGRES_DB
          value: "${POSTGRES_DB}"
        - name: POSTGRES_PASSWORD
          value: "${POSTGRES_PASSWORD}"
        - name: SECRET_KEY_BASE
          value: "${SECRET_KEY_BASE}"
        - name: SIGNING_SALT
          value: "${SIGNING_SALT}"
        - name: ENCRYPTION_SALT
          value: "${ENCRYPTION_SALT}"
        ports:
        - name: http
          containerPort: 4000
