apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sciety
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- serviceaccount.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: discussions
    app.kubernetes.io/instance: discussions--${environment_name}
    app.kubernetes.io/name: bonfire
