apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: sciety-staging
spec:
  allocatedStorage: 20
  dbInstanceClass: db.t3.micro
  dbInstanceIdentifier: sciety-staging
  dbName: postgres
  port: 5432
  engine: postgres
  engineVersion: "13.18"
  masterUsername: "postgres"
  masterUserPassword:
    name: sciety--staging--secret-env-vars
    key: PGPASSWORD
  vpcSecurityGroupIDs:
    - sg-0a04b1c8433227e63
  dbSubnetGroupName: elife-flux-prod-ack-rds-controller-all-dbs
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: sciety-staging-dbinstance-endpoint-address
  namespace: sciety
spec:
  to:
    name: sciety--staging--public-env-vars
    kind: configmap
    key: PGHOST
  from:
    path: ".status.endpoint.address"
    resource:
      group: rds.services.k8s.aws
      kind: DBInstance
      name: sciety-staging
