apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sciety--staging--secret-env-vars
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: sciety--staging--secret-env-vars
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: sciety-team/sciety-staging-secret-vars
