apiVersion: templates.kluctl.io/v1alpha1
kind: ObjectTemplate
metadata:
  name: bonfire-database-secret-transformer
  namespace: database
spec:
  serviceAccountName: bonfire-database-secret-transformer
  prune: true
  matrix:
    - name: secret
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: bonfire-database-app
  templates:
  - object:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "bonfire-database-connection-details"
      stringData:
        PGHOST: "{{ matrix.secret.data.host | b64decode }}"
        PGPORT: "{{ matrix.secret.data.port | b64decode }}"
        PGDATABASE: "{{ matrix.secret.data.dbname | b64decode }}"
        PGPASSWORD: "{{ matrix.secret.data.password | b64decode }}"
        PGUSER: "{{ matrix.secret.data.user | b64decode }}"

        # Support dj-database-url
        DATABASE_URL: "{{ matrix.secret.data[\"jdbc-uri\"] | b64decode }}"

        # other common prefixes
        POSTGRES_HOST: "{{ matrix.secret.data.host | b64decode }}"
        POSTGRES_PORT: "{{ matrix.secret.data.port | b64decode }}"
        POSTGRES_DATABASE: "{{ matrix.secret.data.dbname | b64decode }}"
        POSTGRES_DB: "{{ matrix.secret.data.dbname | b64decode }}"
        POSTGRES_PASSWORD: "{{ matrix.secret.data.password | b64decode }}"
        POSTGRES_USER: "{{ matrix.secret.data.user | b64decode }}"
