---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bonfire--${environment_name}-role-config
data: {}
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: bonfire--${environment_name}-role-config-arn
spec:
  to:
    name: bonfire--${environment_name}-role-config
    kind: configmap
    key: bonfire-role-arn
  from:
    path: ".status.ackResourceMetadata.arn"
    resource:
      group: iam.services.k8s.aws
      kind: Role
      name: bonfire--${environment_name}
